# -*- coding: utf-8 -*-
"""w10 hw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AEphhKXrVwbfKezokFP4472SQfopO48m
"""

cast = ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson', 'Jeremy Renner', 'Don Cheadle', 'Paul Rudd', 'Benedict Cumberbatch', 'Chadwick Boseman', 'Brie Larson', 'Tom Holland', 'Karen Gillan', 'Zoe Saldana', 'Evangeline Lilly']

cast_list = []
print(cast_list)
print(type(cast_list))
print(len(cast_list))

actor_0 = cast_list_a[0].get('alt').strip()
cast_list.append(actor_0)
print(cast_list)

import requests
from bs4 import BeautifulSoup

response = requests.get('https://www.imdb.com/title/tt4154796/')
soup = BeautifulSoup(response.text)

cast_list_a = soup.select("#titleCast .loadlate")
print(len(cast_list_a))

i = 0
while i < len(cast_list_a):
    actor = cast_list_a[i].get('alt').strip()
    cast.append(actor)
    i += 1
print(cast)





