# -*- coding: utf-8 -*-
"""w12 hw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QFf_UXxdRoF0JUVVHeN9hVx0x0HpN0X4
"""

x = int(input("請輸入開始的正整數："))
y = int(input("請輸入終止的正整數："))
odds = []
for i in range(x, y+1):
  mod = i % 2 
  if mod == 1:
    odds.append(i)
print(odds)

print(len(odds)) #記數
print(sum(odds)) #加總

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"]
for idx, movie in enumerate(avengers):
    print("第 {} 部上映的復仇者聯盟電影：{}".format(idx+1, movie))



