# -*- coding: utf-8 -*-
"""w13 hw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WjVja0iikpGQlI5UDCVlZySC3Wct2PAK
"""

from random import sample

sample(range(1, 1001), 1)

from random import sample

n_samples = 0
while True:
    random_integer = sample(range(1, 1001), 1)[0]
    n_samples += 1
    if random_integer % 56 == 0:
        break
print(random_integer)
print(n_samples)

def get_fahrenheit(x):
  """
  Transform a Celsius degree into Farenheit scale
  """
  fah = x *9/5 + 32
  return fah

get_fahrenheit(32)

def get_bmi(height, weight):
  """
  Calculate BMI based on height and weight
  """
  height = height / 100
  bmi = weight / height**2
  return bmi

get_bmi(198, 129)



