# -*- coding: utf-8 -*-
"""w2 hw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dg18FxGZjl8TVF4r7CX0cyiC20qMNi-e
"""

print("Hello World!")

import this