# -*- coding: utf-8 -*-
"""w4 hw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bs9ZSAV1lUkrtY0rbv8lnS3nyroWI3_a
"""

current_celsius = 28
current_fahrenheit = current_celsius * 9 / 5 + 32
print(current_fahrenheit)

current_celsius = (current_fahrenheit - 32) * 5 / 9
print(current_celsius)

shaq_height = 216
shaq_weight = 147
shaq_bmi = shaq_weight / (shaq_height/100) **2
print(shaq_bmi)

ross_said = """Let's put aside the fact that you "accidentally" pick up my grandmother's ring."""
print(ross_said)

current_city = input("請輸入你所在城市:")
weather = input("請輸入目前的天氣:")
print("我在{}，天氣{}" .format(current_city, weather))

shaq_height = 216
shaq_weight = 147
shaq_bmi = shaq_weight / (shaq_height/100) **2
print(shaq_bmi > 24)