# -*- coding: utf-8 -*-
"""w6 hw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sCaaDTbGAjk79Cm2O832HLwqYgimww5t
"""

id_last_digit = input("請輸入您身分證字號的尾數：")
id_last_digit = int(id_last_digit)
modulo = id_last_digit % 2 
print(modulo)
ans = modulo == 1
print(ans)

id_last_digit = input("請輸入您身分證字號的尾數：")
id_last_digit = int(id_last_digit)
modulo = id_last_digit % 2 
print(modulo)
ans = modulo == 1
print(ans)







