# -*- coding: utf-8 -*-
"""w7 hw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jY8ZISMWMSR44uWUD75CHITcK2ia2-h2
"""

salary = input("請輸入月薪:")
saving_account = input("請輸入存款")
salary = int(salary)
saving_account = int(saving_account)

if salary > 40000:
  ans = "發信用卡"
if saving_account >500000:
  ans = "發信用卡"
print(ans)



salary = input("請輸入月薪:")
saving_account = input("請輸入存款")
salary = int(salary)
saving_account = int(saving_account)

if salary > 40000:
  ans = "發信用卡"
if saving_account >500000:
  ans = "發信用卡"
print(ans)

salary = input("請輸入月薪:")
saving_account = input("請輸入存款")
salary = int(salary)
saving_account = int(saving_account)

print(salary > 40000 or saving_account > 500000)

salary = input("請輸入月薪:")
saving_account = input("請輸入存款")
salary = int(salary)
saving_account = int(saving_account)

print(salary > 40000 or saving_account > 500000)

user_int = input("請輸入一個正整數：")
user_int = int(user_int)
if user_int % 2 == 0:
    ans = "偶數"
else:
    ans = "奇數"
print(ans)

user_int = input("請輸入一個正整數：")
user_int = int(user_int)
if user_int % 2 == 0:
    ans = "偶數"
else:
    ans = "奇數"
print(ans)

id_last_id = input("請輸入身分證字號尾數:")
id_last_id = int(id_last_id)
if id_last_id % 2 == 0:
  print("因為身分證字號為偶數，星期二四六日領")
else:
  print("因為身分證字號為奇數，星期一三五日領")

id_last_id = input("請輸入身分證字號尾數:")
id_last_id = int(id_last_id)
if id_last_id % 2 == 0:
  print("因為身分證字號為偶數，星期二四六日領")
else:
  print("因為身分證字號為奇數，星期一三五日領")

input_height = float(input("請輸入身高(公分):"))
input_weight = float(input("請輸入體重(公斤):"))
bmi = input_weight / (input_height*0.01)**2
if bmi > 30:
  label = "Obese"
elif bmi > 25:
  label = "Overweight"
elif bmi > 18.5:
  label = "Normal weight"
if bmi <= 18.5:
  label = "Underweight"
print(label)

input_height = float(input("請輸入身高(公分):"))
input_weight = float(input("請輸入體重(公斤):"))
bmi = input_weight / (input_height*0.01)**2
if bmi > 30:
  label = "Obese"
elif bmi > 25:
  label = "Overweight"
elif bmi > 18.5:
  label = "Normal weight"
if bmi <= 18.5:
  label = "Underweight"
print(label)