# -*- coding: utf-8 -*-
"""w9 hw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AT4sVtfkEkrr8pEfiO_jQu374XPTh4QA
"""

x = int(input("請輸入開始的整數："))
y = int(input("請輸入終止的整數："))
i = x
while i <= y:
  if i % 2 == 1:
    print(i)
  i += 1

x = int(input("請輸入開始的整數："))
y = int(input("請輸入終止的整數："))
i = x
counter = 0 # 歸零
while i <= y:
  if i % 2 == 1:
    counter += 1
  i += 1 
print(counter)

x = int(input("請輸入開始的整數："))
y = int(input("請輸入終止的整數："))
i = x
summation = 0
while i <= y:
  if i % 2 == 1:
    summation += i # 數值累加
  i += 1 
print("======")
print(summation)





